### ISSUE TITLE
Use the full API URL

### ISSUE THREAD

**Issue by synapdk** [AndroidNextdoor/myFirstAngularApi#2]
https://github.com/AndroidNextdoor/myFirstAngularApi/blob/e034075a6822769c384ca172b309c2c5547c8638/src/app/posts.service.ts#L13

The API and the angular app are separate beasties that should be able to run in different places, so you'll likely need to use a full URL to reach the API. I used `http://localhost:3000/api/posts` to make it work.

**Comment by AndroidNextdoor** [comment]
Thank you for pointing me in the right direction there.
